version: '3.7'
services:

  wordpress:
    image: wordpress:latest
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "8088:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      TZ: "Asia/Bangkok"
    networks:
      - backend

  db:
    container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TZ: "Asia/Bangkok"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - backend
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      #PMA_HOST: mariadb
      #PMA_USER: root
      #PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 10240000
      #PMA_ABSOLUTE_URI: https://db.domain.com
      TZ: "Asia/Bangkok"
    ports:
      - "8080:80"
    links:
      - db:db
    networks:
      - backend
    restart: always
    
networks:
  backend:
    external:
      name: backend