version: "3.8"

services:
  # Database
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpnet

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:apache
    depends_on:
      - db
    ports:
      - 8444:80
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: wordpress
    networks:
      - wpnet


  # WordPress
  wordpress:
    image: wordpress:php7.4-apache
    depends_on:
      - db
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 8555:80
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpnet

volumes:
  db_data:

# Optional network for internal communication
networks:
  wpnet:
    driver: bridge

# To access phpMyAdmin, open http://localhost:8080 in your browser.
# Login with the credentials defined in the environment variables.
# Access WordPress at http://localhost:8000 through the browser.
# To install WordPress, follow the on-screen instructions.

